name: Maven, Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
  
    - name: Publish jar to GitHub Packages
      run: mvn -B clean deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build  Docker image
     

    - name: Build and publish Docker image to GitHub Packages
      env:
        DOCKER_IMAGE_TARGET: docker.pkg.github.com/arothuis-hu/notes-boot/notes-boot:latest
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
      run: |
        docker buildx build --load -t ${DOCKER_IMAGE_TARGET} .
        docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker push ${DOCKER_IMAGE_TARGET}
        
