name: Build pipeline

# When should this pipeline run?
# on pushes to master and PRs to master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# What jobs does this workflow consist of?
jobs:
  build:
    # Use ubuntu as an image for our build environment
    runs-on: ubuntu-latest

    # What steps does this job consist of?
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

        # Setup version 12 of Java
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

        # Run all maven phases to deployment
        # with our repository as a target
      - name: Publish jar to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}